namespace EFCore.RowVersion;

internal static class Emitter
{
    public const string AttributeSource =
        """
        // <auto-generated by Swevo.EFCore.RowVersion/>
        #nullable enable
        namespace EFCore.RowVersion;

        /// <summary>Marks an EF Core entity class for compile-time optimistic-concurrency field generation.</summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class OptimisticAttribute : System.Attribute { }
        """;

    public const string InterfaceSource =
        """
        // <auto-generated by Swevo.EFCore.RowVersion/>
        #nullable enable
        namespace EFCore.RowVersion;

        /// <summary>Implemented by all entities decorated with <see cref="OptimisticAttribute"/>.</summary>
        public interface IOptimisticEntity
        {
            /// <summary>EF Core row-version concurrency token.</summary>
            byte[] RowVersion { get; set; }
        }
        """;

    public const string CoreSource =
        """
        // <auto-generated by Swevo.EFCore.RowVersion/>
        #nullable enable
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Threading;
        using System.Threading.Tasks;
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.ChangeTracking;

        namespace EFCore.RowVersion;

        /// <summary>Extension methods for configuring optimistic-concurrency row-version tokens on <see cref="IOptimisticEntity"/> entities.</summary>
        public static class OptimisticModelBuilderExtensions
        {
            /// <summary>
            /// Marks the <see cref="IOptimisticEntity.RowVersion"/> property as a concurrency token
            /// for every entity that implements <see cref="IOptimisticEntity"/>.
            /// Call this inside <c>OnModelCreating</c> after all entities are registered.
            /// For SQL Server, the <c>[Timestamp]</c> attribute on the generated property is also
            /// recognised by convention and configures <c>IsRowVersion()</c> automatically.
            /// </summary>
            public static ModelBuilder AddOptimisticConcurrencyConfiguration(this ModelBuilder modelBuilder)
            {
                foreach (var entityType in modelBuilder.Model.GetEntityTypes())
                {
                    if (!typeof(IOptimisticEntity).IsAssignableFrom(entityType.ClrType))
                        continue;

                    modelBuilder.Entity(entityType.ClrType)
                        .Property(nameof(IOptimisticEntity.RowVersion))
                        .IsConcurrencyToken();
                }

                return modelBuilder;
            }
        }

        /// <summary>Extension methods for saving EF Core changes with optimistic-concurrency retry logic.</summary>
        public static class OptimisticSaveExtensions
        {
            /// <summary>
            /// Saves changes, retrying up to <paramref name="maxRetries"/> times when a
            /// <see cref="DbUpdateConcurrencyException"/> is thrown. On each conflict the
            /// <em>client values win</em>: the database values are reloaded as the new baseline
            /// and the original client changes are re-applied.
            /// </summary>
            public static async Task<int> SaveChangesClientWinsAsync(
                this DbContext context,
                int maxRetries = 3,
                CancellationToken cancellationToken = default)
            {
                for (var attempt = 0; attempt <= maxRetries; attempt++)
                {
                    try
                    {
                        return await context.SaveChangesAsync(cancellationToken);
                    }
                    catch (DbUpdateConcurrencyException ex) when (attempt < maxRetries)
                    {
                        foreach (var entry in ex.Entries)
                        {
                            var dbValues = await entry.GetDatabaseValuesAsync(cancellationToken);
                            if (dbValues != null)
                                entry.OriginalValues.SetValues(dbValues);
                        }
                    }
                }

                return await context.SaveChangesAsync(cancellationToken);
            }

            /// <summary>
            /// Saves changes, retrying up to <paramref name="maxRetries"/> times when a
            /// <see cref="DbUpdateConcurrencyException"/> is thrown. On each conflict the
            /// <em>database values win</em>: the entity is fully reloaded and client changes
            /// are discarded.
            /// </summary>
            public static async Task<int> SaveChangesDatabaseWinsAsync(
                this DbContext context,
                int maxRetries = 3,
                CancellationToken cancellationToken = default)
            {
                for (var attempt = 0; attempt <= maxRetries; attempt++)
                {
                    try
                    {
                        return await context.SaveChangesAsync(cancellationToken);
                    }
                    catch (DbUpdateConcurrencyException ex) when (attempt < maxRetries)
                    {
                        foreach (var entry in ex.Entries)
                            await entry.ReloadAsync(cancellationToken);
                    }
                }

                return await context.SaveChangesAsync(cancellationToken);
            }
        }
        """;

    public static string Emit(TypeModel model) =>
        $$"""
        // <auto-generated by Swevo.EFCore.RowVersion/>
        #nullable enable
        namespace {{model.Namespace}};

        partial class {{model.TypeName}} : global::EFCore.RowVersion.IOptimisticEntity
        {
            /// <inheritdoc/>
            [System.ComponentModel.DataAnnotations.Timestamp]
            public byte[] RowVersion { get; set; } = System.Array.Empty<byte>();
        }
        """;

    public static string EmitTopLevel(string typeName) =>
        $$"""
        // <auto-generated by Swevo.EFCore.RowVersion/>
        #nullable enable

        partial class {{typeName}} : global::EFCore.RowVersion.IOptimisticEntity
        {
            /// <inheritdoc/>
            [System.ComponentModel.DataAnnotations.Timestamp]
            public byte[] RowVersion { get; set; } = System.Array.Empty<byte>();
        }
        """;
}
